import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Inter, Roboto } from "next/font/google"

const inter=Inter({subsets:['latin']})

import Nav from "@/components/navigation/nav";
import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
    <html lang="en">
      <body className={cn('px-6 md:px-12 max-w-7xl mx-auto bg-black',`${inter.className}`)}>
        
       <Nav/>
        {children}
      </body>
    </html>
  );
}
